# Site settings
title: Dawid Kaszuba
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dawidkaszuba.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dawid Kaszuba
user_description: For several years I have been interested in the IT world, in particular Java-related technologies<3 I am a third-year student of Computer Science at the University of Economics in Katowice. I am currently working as Junior Java Developer at Pretius Software Sp. z o.o.
user_title: I'm open to new opportunities
email: d.kaszuba89@gmail.com
# twitter_username: lorem_ipsum
github_username:  dawidkaszuba

exclude: ['package.json', 'src' , 'node_modules']


